### ISSUE TITLE
Width of page content in Desktop view too small

### ISSUE THREAD

**Issue by klues** [asterics/asterics-docs#8]
A manual page currently looks like this:
![Screenshot_2](https://user-images.githubusercontent.com/2537025/70134009-7eaec380-1687-11ea-8f5f-2e30a1e9da58.png)

but I think it should look more like this:
![Screenshot_3](https://user-images.githubusercontent.com/2537025/70134036-8b331c00-1687-11ea-9b7a-a4457ab323e8.png)

The max-width of the main content is just `740px` which to my mind wastes way too much space. It should be e.g. `1280px`, the same value [OpenHab](https://www.openhab.org/docs/) is using.

**Comment by sabicalija** [comment]
We can change it rather easily. However, if we continue using a small width like `740px` there is no big difference with the mobile version and the contents look similar. With a broader `max-width` the two versions (desktop, mobile) may look and feel quite different.

**Comment by sabicalija** [comment]
I like the smaller width, to be honest. I'm using web pages, especially online documentation, very often side-by-side with another application window. I'm not using the browser "full-width" all the time. But I get your point. Whatever the majority wants is fine for me.

**Comment by klues** [comment]
To my mind the point of responsive webdesign is that content adapts to screen size. Therefore I don't think that mobile and desktop version should look the same. If you're using documentation side-by-side that should not be a problem since the content will automatically adapt to the smaller width. (btw: a window with half-screen-width on your screen is still as big as fullscreen on a normal screen 😄)

Maybe discuss again with @deinhofer - it's not the most important issue but it's something that always kind of bothers me when visiting asterics.eu.

**Comment by sabicalija** [comment]
I get the pros and cons of both approaches. Whatever you (all) want is fine with me.

**Comment by sabicalija** [comment]
Another drawback of a wider `max-width` could be, that it's getting harder to read. ^^ It's easier to keep track of the current/next line when the content is not too wide.

**Comment by sabicalija** [comment]
@deinhofer @klues I'm closing the issue again - as discussed today. Here's a link to the article on that matter I mentioned today: https://www.freshconsulting.com/uiux-principle-46-text-box-width-should-help-users-read/.

However, the `740px` (current setting) may be too small. In case we agree that we want a wider max-width, reopen the issue again, please. The article, on the other hand, recommends `700px` for substantive texts. An alternative approach would be to change the "design" of the page so that we make more use of it, without having to change the `max-width` of texts.
